  #  secretKey:  BASE64_ENCODED_VALUE
  # echo -n 'username' | base64
apiVersion: v1
kind: Secret
metadata:
  name:  mysql-secret
type: Opaque
data:
   mysql_password: MTIzNA==       #1234
   mysql_root_password: c2VjcmV0  #secret
---
apiVersion: v1
kind: Secret
metadata:
  name:  postgres-secret
type: Opaque
data:
   postgres_password: cGFzcw==
---
apiVersion: v1
kind: Secret
metadata:
  name:  mongo-secret
type: Opaque
data:
   mongo_password: bW9uZ29kYlNlY3JldA==