apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        volumeMounts:
          - name: game-data
            mountPath: /var/lib/postgresql/data
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres_password
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: myconfigmap
                key: postgres_user
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: myconfigmap
                key: postgres_db
        ports:
        - containerPort: 5432
      restartPolicy: Always
      volumes:
        - name: game-data
          hostPath:
            path: /gameData
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app:  postgres
  type:  ClusterIP
  ports:
  - protocol:  TCP
    port:  5432
    targetPort:  5432