apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        volumeMounts:
          - name: user-data
            mountPath: /var/lib/mysql
        env:
          - name: MYSQL_USER
            valueFrom:
                configMapKeyRef:
                  name: myconfigmap
                  key:  mysql_user
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_root_password
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: myconfigmap
                key: mysql_database
        # resources:
        #   limits:
        #     cpu: "1"
        #     memory: 512Mi
        #   requests:
        #     cpu: 500m
        #     memory: 256Mi
        ports:
        - containerPort: 3306
      restartPolicy: Always
      volumes:
        - name: user-data
          hostPath:
            path: /data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name:  mysql-service
spec:
  selector:
    app:  mysql
  type:  ClusterIP
  ports:
  - protocol: TCP
    port:  3306
    targetPort:  3306